aws-lb-controller:
  # IMDSv2 is enabled
  region: us-east-1
  vpcId: vpc-01ab44431f5597901
  clusterName: eks-playground
  serviceAccount:
    name: aws-lb-controller
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::437023642520:role/eks-playground-aws-lb-controller
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
