application:
  applicationName: foo
  deployment:
    env:
      SERVICE:
        value: "foo"
      AGENT_HOSTNAME:
        value: 1.2.3.4
      BAR_ENDPOINT:
        value: http://bar.bar.svc.cluster.local
    image:
      repository: 437023642520.dkr.ecr.us-east-2.amazonaws.com/foo
      tag: 268ce602ed307b87e70ae5e773fa71155e9d2ea0
    resources:
      limits:
        memory: 64Mi
        cpu: 0.1
      requests:
        memory: 64Mi
        cpu: 0.05
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
  service:
    ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 5000
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: bar
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/target-type: ip
    pathType: Prefix
    hosts:
      - host: foo.sandbox.lgtm.vtatarin.xyz
