application:
  applicationName: foo
  deployment:
    env:
      SERVICE:
        value: "foo"
      AGENT_HOSTNAME:
        value: 1.2.3.4
      BAR_ENDPOINT:
        value: bar.bar.svc.cluster.local
    image:
      repository: 437023642520.dkr.ecr.us-east-2.amazonaws.com/foo
      tag: 280e56f888228bed03f6638087a6af1b61d12a13
    resources:
      limits:
        memory: 64Mi
        cpu: 0.1
      requests:
        memory: 64Mi
        cpu: 0.05
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
  service:
    ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 5000
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
    hosts:
      - host: foo.sandbox.lgtm.vtatarin.xyz
        paths: 
        - path: /
