tempo:
  metaMonitoring:
    serviceMonitor:
      enabled: true
  serviceAccount:
    create: true
    name: tempo
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::437023642520:role/eks-sandbox-tempo
  storage:
    trace:
      backend: s3
      s3:
        endpoint: s3.us-east-1.amazonaws.com
        region: us-east-1
        bucket: eks-sandbox-tempo-1
  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
    zipkin:
      enabled: false
    jaeger:
      thriftHttp:
        enabled: false
    opencensus:
      enabled: false
