external-dns:
  provider: aws
  aws:
    region: us-east-1
    zoneType: public
  domainFilters:
    - sandbox.lgtm.pvlbnkl.xyz
  serviceAccount:
    name: external-dns
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::245582572290:role/eks-sandbox-external-dns
  serviceMonitor:
    enabled: true
