alloy:
  controller:
    type: 'statefulset'
    replicas: 2
  crds:
    create: true
  serviceMonitor:
    enabled: true
  alloy:
    clustering:
      enabled: true
    configMap:
      create: true
      content: |-
        prometheus.remote_write "primary" {
          endpoint {
            url = "http://mimir-nginx.mimir.svc.cluster.local:80/api/v1/push"
          }
        }

        prometheus.operator.podmonitors "primary" {
          forward_to = [prometheus.remote_write.primary.receiver]
          clustering {
            enabled = true
          }
        }

        prometheus.operator.servicemonitors "primary" {
          forward_to = [prometheus.remote_write.primary.receiver]
          clustering {
            enabled = true
          }
        }
