alloy:
  controller:
    type: 'statefulset'
    replicas: 2
  crds:
    create: true
  serviceMonitor:
    enabled: true
  alloy:
    clustering:
      enabled: true
    configMap:
      create: true
      content: |-
        // Monitoring
        prometheus.remote_write "main" {
          endpoint {
            url = "http://mimir-nginx.mimir.svc.cluster.local:80/api/v1/push"
          }
        }

        prometheus.operator.podmonitors "main" {
          forward_to = [prometheus.remote_write.main.receiver]
          clustering {
            enabled = true
          }
        }

        prometheus.operator.servicemonitors "main" {
          forward_to = [prometheus.remote_write.main.receiver]
          clustering {
            enabled = true
          }
        }

        // Generic discovery
        discovery.kubernetes "pods" {
          role = "pod"
        }

        // Logging
        loki.write "main" {
          endpoint {
            url = "http://loki-gateway.loki.svc.cluster.local:80/loki/api/v1/push"
          }
        }

        loki.source.kubernetes "main" {
          targets    = discovery.kubernetes.pods.targets
          forward_to = [loki.write.main.receiver]
        }
