alloy:
  controller:
    type: 'statefulset'
    replicas: 2
  crds:
    create: true
  serviceMonitor:
    enabled: true
  alloy:
    clustering:
      enabled: true
    configMap:
      create: true
      content: |-
        // Monitoring
        prometheus.remote_write "main" {
          endpoint {
            url = "http://mimir-nginx.mimir.svc.cluster.local:80/api/v1/push"
          }
        }

        prometheus.operator.podmonitors "main" {
          forward_to = [prometheus.remote_write.main.receiver]
          clustering {
            enabled = true
          }
        }

        prometheus.operator.servicemonitors "main" {
          forward_to = [prometheus.remote_write.main.receiver]
          clustering {
            enabled = true
          }
        }

        // Generic discovery
        discovery.kubernetes "pods" {
          role = "pod"

          // attach_metadata {
          //   node = true
          // }
        }

        discovery.relabel "pods" {
          targets = discovery.kubernetes.pods.targets

          rule {
            source_labels = ["__meta_kubernetes_namespace"]
            target_label = "k8s_namespace"
          }
        }

        // Logging
        loki.write "main" {
          endpoint {
            url = "http://loki-gateway.loki.svc.cluster.local:80/loki/api/v1/push"
          }
        }

        loki.source.kubernetes "main" {
          targets    = discovery.relabel.pods.output
          forward_to = [loki.write.main.receiver]

          clustering {
            enabled = true
          }
        }
