name: Terraform CI/CD

on:
  push:
    branches:
    - main
    # paths:
    # - terraform/**
  pull_request:
    branches:
    - main
    # paths:
    # - terraform/**

permissions:
 id-token: write
 contents: read

jobs:
 terraform:
   runs-on: ubuntu-22.04
   steps:
     - name: Git clone the repository
       uses: actions/checkout@v4
     - name: configure aws credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
         aws-region: ${{ env.AWS_REGION }}
     # Upload a file to AWS s3
     - name: test
       id: test
       run: |
          aws s3 ls
